name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5 # Update to the Terraform version you're using

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 # Update to your AWS region

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform changes
        run: terraform plan \
          -var="civo_api_key=${{ secrets.CIVO_API_KEY }}" \
          -var="civo_region=${{ secrets.CIVO_REGION }}"

      - name: Apply Terraform
        run: terraform apply -auto-approve \
          -var="civo_api_key=${{ secrets.CIVO_API_KEY }}" \
          -var="civo_region=${{ secrets.CIVO_REGION }}"
